### ISSUE TITLE
How do I install it

### ISSUE THREAD

**Issue by davodogster** [umr-amap/aRchi#1]
Hi I have TLS data of forests. 

These scripts look promising! .. How do I install your R package?

Regards,
Sam

**Comment by davodogster** [comment]
@oliviermartin7 Hi, I was able to install aRchi using similar instructions to BIOMASS. Now my question is related to QSM. Can aRchi compute QSM off a single tree leaf+wood pointcloud? Or does archi not perform QSM calculations? Does it assume you already have the QSM from some other software ? Cheers, Sam

**Comment by oliviermartin7** [comment]
Hi,
Cool that your were able to install the package. For now, aRchi does not compute QSM. You have to import it using read_QSM function and different model format are accepted (treeQSM, simpletree, simpleforest....). 
In a following version, a function to compute QSM will be available. However we did not plan for now to implement a wood leaf segmentation function.
Best,
Olivier

**Comment by oliviermartin7** [comment]
@davodogster Now V 2.1.0 makes possible generating QSMs. 

Thanks @Blecigne !
