### ISSUE TITLE
move nodes that have been misplaced + export MTG

### ISSUE THREAD

**Issue by Micbut** [umr-amap/aRchi#11]
Hi!
Is it possible to change the position of nodes, add child nodes and correct topology as it is doable with PlantScan3d?
Also: is it possible to export the the topology in an MTG file?

**Comment by oliviermartin7** [comment]
Hi,

No it is not possible for now to export MTG file. 

If you want to edit your QSM, you can use AMAP-studio scan. You have to export your QSM in .txt and rearrange it in order to match the column order require in AMAP-studio scan. https://amapstudio.cirad.fr/soft/scan/start

Best
