### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Saadi4469** [umr-amap/aRchi#2]
Hello,

Your package seems pretty cool. Any update on computing QSM through aRchi? This function would be highly helpful to me as the only other package I know of that computes QSM is 'TreeQSM'. But TreeQSM is in MATLAB, and I don't have MATLAB. For now is there any other way to compute QSM in R or any other software on Windows?

Cheers,

**Comment by GreKro** [comment]
Hi !

To create QSMs from point clouds you can use also SimpleForest software developed by Jan Hackenberg - https://www.simpleforest.org/pages/download.html

Cheers,

**Comment by oliviermartin7** [comment]
@Saadi4469 

Now V 2.1.0 makes possible generating QSMs. 

Thanks @Blecigne !
