### ISSUE TITLE
Read QSM created with Simple Forest

### ISSUE THREAD

**Issue by GiulioDonatiSarti** [umr-amap/aRchi#4]
Hi Olivier,
first of all I would like to thank you for your work; it is really interesting! 

However, at the moment, I have some problems working with it.... 

I have obtained a QSM from a TLS point cloud with the SimpleForest plug-in in CompuTree. Now I would like to use your package to extract some information from the QSM, but I am not able to read the .csv file and build an object of class aRchi. In fact, when I run the build_aRchi() command I get the following message:
Paths is empty
Point cloud: 49130 points 
Node table is empty
No operation realized

Any idea where I might be going wrong?

Thank you very much in advance,
Giulio

For completeness I attach: (i) the .csv file of the QSM obtained from SimpleForest, (ii) the .txt file related to the point cloud and (iii) a copy of the code I am trying to use.
 
[Code.txt](https://github.com/umr-amap/aRchi/files/7514511/Code.txt)
[Albero_04_QSM.csv](https://github.com/umr-amap/aRchi/files/7514519/Albero_04_QSM.csv)
[Albero_04.txt](https://github.com/umr-amap/aRchi/files/7514521/Albero_04.txt)

**Comment by GiulioDonatiSarti** [comment]
I just renamed two columns of the .csv and all works.

Specifically, I changed the name of:
branchID > BranchID;
branchOrder > BranchOrder.

**Comment by oliviermartin7** [comment]
Hi Giulio,
Sorry for the late reply. I did not see it...
Great that you managed to read you QSM.
Thanks for reporting the bug. I'll correct it in the next version (2.0.0). Very soon.

Olivier

**Comment by oliviermartin7** [comment]
Now V 2.1.0 makes possible generating QSMs. 

Thanks @Blecigne !
